baseURL = "https://uapi-group.org/kernel-features"
languageCode = "en-us"
title = "UAPI Group Kernel Feature Ideas"
theme = "hugo-book"

[[menu.before]]
  name = "⬅️  Back to top"
  url = "https://uapi-group.org/"
  weight = 1

[[menu.after]]
  name = "Collaborate on Github"
  url = "https://github.com/uapi-group/kernel-features"
  weight = 11

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[params]
  BookPortableLinks = true
  BookRepo = 'https://github.com/uapi-group/kernel-features'
  BookCommitPath = 'commit'
  BookEditLink = '{{ .Site.Params.BookRepo }}/edit/main/{{ .Path }}'
  BookIndexPage = 'README.md'

[modules]
  [[module.mounts]]
    source = '../README.md'
    target = 'content/_index.md'
